const squirrelFacts = [
  "Grey squirrels are the most common type of squirrel found in Central Park.",
  "Cinnamon squirrels, also known as red squirrels, have a reddish-brown fur coat.",
  "Black squirrels have a genetic mutation that causes their fur to be black instead of grey.",
  "Squirrels are rodents, which means their front teeth never stop growing!",
  "Squirrels have excellent vision and a wide field of view.",
  "Squirrels communicate with each other through various vocalizations and tail movements.",
  "Squirrels have a natural instinct to hoard food for the winter months.",
  "Squirrels are very agile and can jump up to 10 times their body length.",
  "Grey squirrels can run at speeds of up to 20 miles per hour.",
  "Squirrels' tails help them balance while jumping and provide shade from the sun.",
  "Squirrels have a natural instinct to bury their food, but they don't always remember where they hid it!",
  "Squirrels are omnivores, meaning they eat both plants and small insects.",
  "Squirrels are known to steal food from other animals, such as birds and even humans!",
  "Cinnamon squirrels are more commonly found in the western parts of the United States.",
  "Black squirrels are more common in certain parts of North America, including parts of Canada and the northeastern United States.",
  "Squirrels' front paws have four toes and their back paws have five toes.",
  "Squirrels are excellent climbers and can scale trees and buildings with ease.",
  "Squirrels are diurnal, which means they are most active during the day.",
  "Squirrels' nests, called dreys, are usually made of twigs, leaves, and other materials.",
  "Squirrels can survive falls from great heights thanks to their small size and lightweight bodies.",
  "Squirrels are known to chew on things like tree bark and even electrical wires!",
  "Squirrels are territorial animals and will defend their territory from other squirrels.",
  "Squirrels have a sharp sense of smell, which helps them locate food and avoid predators.",
  "Squirrels have a lifespan of around 5 to 10 years in the wild.",
  "Grey squirrels can be found in various habitats, including forests, parks, and urban areas.",
  "Cinnamon squirrels are also known for their feisty behavior, especially when defending their territory.",
  "Black squirrels are not a separate species; they are a color variation of the grey squirrel.",
  "Squirrels are known to carry diseases like rabies and Lyme disease, so it's best to admire them from a distance.",
  "Squirrels are known for their acrobatic skills, often performing daring jumps and leaps.",
  "Squirrels are opportunistic feeders and will eat whatever food is available to them.",
  "Squirrels are excellent swimmers and can use their tails as a rudder while in the water.",
  "Squirrels are known to make multiple nests within their territory for different purposes.",
  "Grey squirrels are known to have a varied diet, including nuts, seeds, fruits, and even bird eggs.",
  "Cinnamon squirrels are named for their cinnamon-colored fur, which can range from light brown to deep red.",
  "Black squirrels are sometimes mistaken for other species of squirrels, such as chipmunks or ground squirrels.",
  "Squirrels' teeth never stop growing, so they need to gnaw on hard objects to keep them trimmed.",
  "Squirrels have a highly developed sense of touch, particularly in their paws.",
  "Squirrels play an important role in forest ecosystems by dispersing seeds and helping with plant regeneration.",
  "Squirrels are known to be curious animals, often exploring their surroundings and investigating new objects.",
  "Squirrels are prey animals and have many predators, including birds of prey, snakes, and even domestic cats.",
  "Squirrels have a thick fur coat that helps keep them warm during the winter months.",
  "Squirrels are known to be very adaptable animals, able to thrive in a variety of environments.",
  "Squirrels are social animals and will often gather in groups, especially during the mating season.",
  "Squirrels have a keen sense of hearing, which helps them detect potential threats.",
  "Squirrels are known for their ability to quickly dart away from danger, using their speed and agility to escape predators.",
  "Squirrels are known to exhibit playful behavior, often chasing each other and engaging in mock fights.",
  "Squirrels have a relatively short gestation period, with pregnancies lasting around 44 days.",
  "Squirrels are known to have excellent memory, often remembering the locations of their food caches months later.",
];

module.exports = squirrelFacts;
